### ISSUE TITLE
Insert Extracted Text Into a Single Callout

### ISSUE THREAD

**Issue by blankster** [jmilldotdev/obsidian-wikipedia#7]
Thanks a lot for your plugin 👏

I'm wondering if there is some way to combine the extracted text:

```
{{text}}
> [Wikipedia]({{url}})

```
To a single callout:
```
> [!quote]
> {{paragraphText}}
>
```

Without getting the template multiple times inserted for each paragraph?

That's what I aim for (term: Regression Testing):

![image](https://user-images.githubusercontent.com/1443109/185766817-36ff04f0-5dbd-4082-8b4a-994a84e966e1.png)

That's what I get with the current template:
![image](https://user-images.githubusercontent.com/1443109/185766825-0bcd5585-dc9a-4a4b-a96d-9685d810a30e.png)

If there is any way to achieve this currently, please let me know!

**Comment by valenzine** [comment]
This is quite easy to achieve.

You just need to set up the **Wikipedia Extract Template** like this:

```
> [!quote]
{{text}}
> [Wikipedia]({{url}})
```

And then make sure to change the **Paragraph Template** as well.

```
> {{paragraphText}}
>

```
