### ISSUE TITLE
Interwiki links

### ISSUE THREAD

**Issue by Calorion** [jmilldotdev/obsidian-wikipedia#8]
This plugin is great, but what I'd really like is the ability to use [Interwiki](https://en.wikipedia.org/wiki/Help:Interwiki_linking) links in Obsidian, so that I could type `[[w:apple]]` and the plugin would transform that into a link to https://en.wikipedia.org/wiki/Apple

**Comment by jmilldotdev** [comment]
use a keyboard text expander and this can be achieved

**Comment by Calorion** [comment]
True, but it would be a very useful addition to the plugin regardless.

**Comment by Calorion** [comment]
Well, yes, but that presumes I’ll never want to use `w:` for any other purpose. Which, maybe. But it would still be a very useful addition to this plugin.
